=== aparedes1204/Mexify/xml/comments.dtd
<!ELEMENT songs (song)*>
<!ELEMENT song (comments)>
<!ATTLIST song id ID #REQUIRED>
<!ELEMENT comments (comment)*>
<!ELEMENT comment (author, date, review)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT review (#PCDATA)>

=== aparedes1204/Mexify/xml/comments.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE songs SYSTEM "comments.dtd">
<songs>
    <song id="1">
        <comments>
            <comment>
                <author>proba002@ikasle.ehu.eus</author>
                <date>2021-11-15T16:13:59+01:00</date>
                <review>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas gravida hendrerit nunc molestie viverra. Sed eget dui ut odio aliquam tempor. Donec ultrices consectetur leo, non vehicula urna rhoncus rhoncus. Fusce aliquam accumsan est, sit amet posuere est rutrum eget. Donec vehicula ultrices dolor, in pellentesque odio malesuada non. Ut elit magna, fermentum eget lectus in, scelerisque pellentesque risus. Nam vel porttitor lectus. Maecenas ut sollicitudin mauris. Phasellus euismod lorem sed felis tincidunt, id euismod est sagittis. Cras volutpat, ipsum sed elementum dapibus, massa sapien lobortis justo, ut porta mauris ipsum eget justo. Proin a congue ex. In felis magna, posuere sit amet nunc sit amet, scelerisque sodales nisl.</review>
            </comment>
            <comment>
                <author>proba001@ikasle.ehu.eus</author>
                <date>2021-12-08T18:23:12+01:00</date>
                <review>Morbi vulputate, risus a tempor vulputate, libero orci venenatis justo, ut tincidunt metus nibh suscipit erat. Quisque ornare elementum ligula quis lacinia. Quisque eget leo gravida, porta sem vitae, pulvinar mi. Aliquam vulputate maximus odio nec sollicitudin. Praesent id felis quis purus pulvinar consequat nec nec sem. Aliquam faucibus turpis eu nisi finibus, quis condimentum elit lacinia. Integer tempus, tortor at tempus mollis, arcu libero ultrices est, nec commodo magna magna sit amet sapien. Suspendisse feugiat vulputate lacus ac suscipit.</review>
            </comment>
            <comment>
                <author>proba002@ikasle.ehu.eus</author>
                <date>2021-12-08T18:30:12+01:00</date>
                <review>Ut finibus facilisis dolor at mattis. Mauris vel tempus arcu. Morbi aliquam arcu a consectetur semper. Nullam eleifend aliquet ante, sed fringilla mauris varius at. Quisque efficitur elit vitae metus sagittis, vitae posuere elit tempor. Proin sapien arcu, hendrerit sit amet maximus id, laoreet eu elit. Fusce ex enim, bibendum vitae nunc nec, feugiat dapibus mauris. Nunc neque odio, pharetra a justo quis, laoreet sollicitudin neque.</review>
            </comment>
            <comment>
                <author>proba001@ikasle.ehu.eus</author>
                <date>2021-12-09T00:22:23+01:00</date>
                <review>Aenean orci urna, rhoncus non vehicula vitae, mollis in leo. Nullam in scelerisque lacus. In malesuada at felis et faucibus. Aliquam at velit quis nunc consectetur pulvinar a at ante. Nulla aliquet luctus velit sit amet rutrum. Nulla lobortis dolor fringilla lectus placerat ornare. Aliquam et lacus eget dui mollis cursus. Nullam id fringilla nunc. Nullam accumsan libero eu aliquam scelerisque. Aenean finibus arcu sed mi ullamcorper mattis.</review>
            </comment>
        </comments>
    </song>
    <song id="2">
        <comments>
            <comment>
                <author>proba002@ikasle.ehu.eus</author>
                <date>2021-11-20T16:13:59+01:00</date>
                <review>Maecenas at neque vel lorem tristique ullamcorper. Nulla egestas ac odio in congue. Suspendisse et urna id justo vehicula volutpat et lobortis arcu. Nam laoreet, tortor id mollis pulvinar, velit diam tempor metus, eu molestie elit metus at libero. In in auctor neque, sit amet ornare enim. Sed eget interdum elit, quis egestas nisl. Nullam nulla nibh, bibendum vitae tellus nec, consequat tempus velit. Fusce vestibulum dignissim magna at fermentum. Proin in vehicula elit. Quisque at tincidunt diam. Duis volutpat nunc sed felis ultrices, ac blandit nulla pulvinar. Morbi sed magna ut lacus tincidunt congue non eu elit.</review>
            </comment>
        <comment><author>proba001@ikasle.ehu.eus</author><date>2021-12-09T22:35:59+01:00</date><review>Proin vel augue faucibus, aliquet nulla ac, sagittis diam. Sed justo mauris, fermentum at ornare vitae, blandit at quam. Phasellus in nisi scelerisque, vulputate mi vitae, blandit sapien. Cras sed rutrum mauris. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer magna est, aliquet vitae tristique et, molestie ac ipsum. Maecenas mollis accumsan efficitur. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris et gravida diam, non egestas ipsum. Nunc scelerisque, tellus ac tristique ultricies, lorem tortor gravida est, eget vulputate tellus tellus ac sapien. Pellentesque eget malesuada elit. Sed eros est, commodo consequat malesuada a, varius eget massa. Praesent nec nunc id mi dictum tincidunt sit amet ut leo. Cras velit elit, malesuada nec mauris vel, rutrum vestibulum purus. Proin vitae facilisis nisi, et vehicula dolor. Proin pharetra eget orci eget venenatis.</review></comment></comments>
    </song>
      <song id="3">
        <comments>
        </comments>
    </song>
      <song id="4">
        <comments>
        <comment><author>proba001@ikasle.ehu.eus</author><date>2021-12-09T22:34:50+01:00</date><review>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla blandit, felis nec egestas rutrum, mauris quam dapibus tellus, sit amet tristique ex dolor a neque. Praesent odio tortor, ultrices sed sapien vitae, mollis rhoncus ante. Sed faucibus, dolor a dictum porttitor, lectus ex sodales elit, non sodales magna ante id nulla. Cras ex ex, volutpat non condimentum quis, semper in lacus. Aliquam erat volutpat. Phasellus tempor iaculis turpis a dapibus. Aenean faucibus, dui eu vehicula porttitor, eros lectus semper sapien, quis lobortis lectus dui pretium nisl. Suspendisse molestie laoreet auctor. Donec scelerisque a metus ac semper. Duis eget rutrum nibh.</review></comment></comments>
    </song>
</songs>
